# frozen_string_literal: true

module Iroh
  module Tasks
    module PublicApiInventory
      HEADER = [
        "# iroh-ruby public API inventory",
        "# Generated by Iroh::Tasks::PublicApiInventory.snapshot"
      ].freeze

      module_function

      def snapshot
        require "iroh"

        lines = HEADER.dup
        lines << "Iroh::VERSION=#{Iroh::VERSION}"
        lines << "Iroh::IROH_FFI_VERSION=#{Iroh::IROH_FFI_VERSION}"

        Iroh.singleton_methods(false).map(&:to_s).sort.each do |method_name|
          lines << "Iroh.#{method_name}"
        end

        Iroh::PUBLIC_CONSTANTS.map(&:to_s).sort.each do |constant_name|
          klass = Iroh.const_get(constant_name)
          lines << "Iroh::#{constant_name}"

          klass.singleton_methods(false).map(&:to_s).sort.each do |method_name|
            lines << "Iroh::#{constant_name}.#{method_name}"
          end

          klass.instance_methods(false).map(&:to_s).sort.each do |method_name|
            lines << "Iroh::#{constant_name}##{method_name}"
          end
        end

        "#{lines.join("\n")}\n"
      end
    end
  end
end
