# frozen_string_literal: true

module Iroh
  module Tasks
    module PublicApiInventory
      HEADER = [
        "# iroh-ruby public API inventory",
        "# Generated by Iroh::Tasks::PublicApiInventory.snapshot"
      ].freeze

      module_function

      def snapshot
        require "iroh"

        lines = HEADER.dup
        lines << "Iroh::VERSION=#{Iroh::VERSION}"
        lines << "Iroh::IROH_FFI_VERSION=#{Iroh::IROH_FFI_VERSION}"

        Iroh.singleton_methods(false).map(&:to_s).sort.each do |method_name|
          lines << "Iroh.#{method_name}"
        end

        Iroh::PUBLIC_CONSTANTS.map(&:to_s).sort.each do |constant_name|
          append_constant(lines, Iroh, "Iroh", constant_name)
        end

        Iroh::PUBLIC_RUBY_CONSTANTS.sort_by { |constant_name, _children| constant_name.to_s }.each do |constant_name, children|
          append_constant(lines, Iroh, "Iroh", constant_name)
          parent = Iroh.const_get(constant_name)
          children.map(&:to_s).sort.each do |child_name|
            append_constant(lines, parent, "Iroh::#{constant_name}", child_name)
          end
        end

        "#{lines.join("\n")}\n"
      end

      def append_constant(lines, container, namespace, constant_name)
        klass = container.const_get(constant_name)
        lines << "#{namespace}::#{constant_name}"

        klass.singleton_methods(false).map(&:to_s).sort.each do |method_name|
          lines << "#{namespace}::#{constant_name}.#{method_name}"
        end

        klass.instance_methods(false).map(&:to_s).sort.each do |method_name|
          lines << "#{namespace}::#{constant_name}##{method_name}"
        end
      end
    end
  end
end
